image:
  - Visual Studio 2015
  - Visual Studio 2022

platform: x64
configuration: Release

version: ci.{build}

build:
  parallel: false
  project: QuantLib.sln
  verbosity: normal

for:
-
  matrix:
    only:
      - image: Visual Studio 2015
  before_build:
    - COPY .appveyor\VS2015.props .\Build.props
-
  matrix:
    only:
      - image: Visual Studio 2022
  before_build:
    - COPY .appveyor\VS2022.props .\Build.props
    - COPY .appveyor\Unity.props .\Directory.Build.props
  test_script:
    - .\test-suite\bin\QuantLib-test-suite-x64-mt.exe --log_level=message --build_info=yes

