
language: cpp

os: linux
dist: trusty
sudo: required
compiler: gcc
services: docker

cache: ccache

env:
  global:
    - DOCKER_OPTS="--rm -ti -v ${HOME}/.ccache:/root/.ccache -v ${TRAVIS_BUILD_DIR}:/build -w /build"
  matrix:
    # Regression test with old Boost version, gcc 4.8
    - DOCKER_IMAGE=lballabio/quantlib-devenv:1.54.0-trusty
      CACHEDCC="ccache gcc" CACHEDCXX="ccache g++"
      CXXFLAGS="-O2 -Wall -Wno-unknown-pragmas -Werror -std=c++03"
    # Boost 1.66, gcc 5.4, strict C++03 mode
    - DOCKER_IMAGE=lballabio/quantlib-devenv:1.66.0-xenial
      CACHEDCC="ccache gcc" CACHEDCXX="ccache g++"
      CXXFLAGS="-O2 -Wall -Wno-unknown-pragmas -Werror -std=c++03"
    # Boost 1.66, gcc 6.3, C++11 mode
    - DOCKER_IMAGE=lballabio/quantlib-devenv:1.66.0-zesty
      CACHEDCC="ccache gcc" CACHEDCXX="ccache g++"
      CXXFLAGS="-O2 -Wall -Wno-unknown-pragmas -Wno-deprecated-declarations -Werror -std=c++11"
    # Latest Boost, gcc 7.3, C++14 mode
    - DOCKER_IMAGE=lballabio/quantlib-devenv:bionic
      CACHEDCC="ccache gcc" CACHEDCXX="ccache g++"
      CXXFLAGS="-O2 -Wall -Wno-unknown-pragmas -Wno-deprecated-declarations -Werror -std=c++14"
    # Latest Boost, clang 6.0
    - DOCKER_IMAGE=lballabio/quantlib-devenv:bionic
      CACHEDCC="ccache clang" CACHEDCXX="ccache clang++"
      CXXFLAGS="-O2 -Wall -Wno-unknown-pragmas -Wno-deprecated-declarations -Werror"

before_install:
  - docker pull ${DOCKER_IMAGE}

script:
  - docker run ${DOCKER_OPTS} ${DOCKER_IMAGE} ./autogen.sh
  - docker run ${DOCKER_OPTS} ${DOCKER_IMAGE} ./configure --disable-static CC="${CACHEDCC}" CXX="${CACHEDCXX}" CXXFLAGS="${CXXFLAGS}"
  - docker run ${DOCKER_OPTS} ${DOCKER_IMAGE} ccache --zero-stats
  - docker run ${DOCKER_OPTS} ${DOCKER_IMAGE} ccache --max-size=2.5G
  - docker run ${DOCKER_OPTS} ${DOCKER_IMAGE} ccache --show-stats
  - docker run ${DOCKER_OPTS} ${DOCKER_IMAGE} make -j 2
  - docker run ${DOCKER_OPTS} ${DOCKER_IMAGE} ccache --show-stats
  - docker run ${DOCKER_OPTS} ${DOCKER_IMAGE} ./test-suite/quantlib-test-suite --log_level=message -- --faster

