name: Check doc generation
on: [push, pull_request]
permissions:
  contents: read

jobs:
  docs:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: |
        rm -f /usr/local/bin/2to3
        brew update
        brew install automake boost doxygen graphviz
        ./autogen.sh
        ./configure
    - name: Doxygen version
      run: |
        doxygen --version
    - name: Check
      run: |
        make docs
