name: Check CMake file list and VC++ projects
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  filelists:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Setup
      run: |
        sudo rm /etc/apt/sources.list.d/microsoft-prod.list
        sudo apt update
        sudo apt install -y libboost-dev
    - name: Configure
      run: |
        ./autogen.sh
        ./configure
    - name: Check
      run: |
        ./tools/check_filelists.sh
