name: Update generated headers
on: [push, pull_request]
jobs:
  filelists:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: |
        sudo apt update
        sudo apt install -y libboost-dev
    - name: Configure
      run: |
        ./autogen.sh
        ./configure
    - name: Update headers
      run: |
        make dist
        rm QuantLib-*.tar.gz
    - uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: update-generated-headers-${{ github.ref }}
        delete-branch: true
        commit-message: 'Update generated headers'
        title: 'Update generated headers'
        author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
