name: Update old license links
on:
  push:
    branches:
      - '**'
jobs:
  namespaces:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Check
      run: |
        shopt -s globstar
        sed -i -e 's|http://quantlib\.org/license\.shtml|https://www.quantlib.org/license.shtml|g' **/*.[hc]pp **/*.ac **/*.docs **/*.cfg **/*.sh **/*.el
    - uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.MACHINE_ACCOUNT_PAT }}
        push-to-fork: ${{ vars.MACHINE_ACCOUNT }}/QuantLib
        branch: update-license-links-${{ github.ref_name }}
        delete-branch: true
        commit-message: 'Update old license links'
        title: 'Update old license links'
        author: lballabio[bot] <224797326+lballabio-bot@users.noreply.github.com>
