name: Mac OS build
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: [macos-11]
            shortname: default-11
          - os: [macos-12]
            shortname: default-12
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: |
        brew install automake boost ccache
    - name: Cache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: macos-ci-build-${{ matrix.shortname }}-${{ github.ref }}
        restore-keys: |
          macos-ci-build-${{ matrix.shortname }}-${{ github.ref }}
          macos-ci-build-${{ matrix.shortname }}-refs/heads/master
          macos-ci-build-${{ matrix.shortname }}-
    - name: Build
      run: |
        ./autogen.sh
        ./configure --disable-shared ${{ matrix.configureflags }} CC="ccache clang" CXX="ccache clang++" CXXFLAGS="-O2 -g0 -Wall -Werror -stdlib=libc++ -mmacosx-version-min=10.9 ${{ matrix.cxxflags }}" LDFLAGS="-stdlib=libc++ -mmacosx-version-min=10.9"
        make -j 3
    - name: Run tests
      run: |
        ./test-suite/quantlib-test-suite --log_level=message
    - name: Run examples
      run: |
        make -C Examples check-examples
