name: Mac OS build
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15]
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        brew install automake boost ccache
    - name: Cache
      uses: actions/cache@v2
      with:
        path: ~/Library/Caches/ccache
        key: ${{ matrix.os }}-build-${{ github.ref }}-${{ github.head_ref }}-${{ hashFiles('**/*.hpp', '**/*.cpp', '**/macos.yml') }}
        restore-keys: |
          ${{ matrix.os }}-build-${{ github.ref }}-${{ github.head_ref }}-
          ${{ matrix.os }}-build-${{ github.ref }}-
          ${{ matrix.os }}-build-refs/heads/master-
          ${{ matrix.os }}-build-
    - name: Build
      env:
        CXXFLAGS: -O2 -g0 -Wall -Werror -Wno-c++11-extensions -stdlib=libc++ -mmacosx-version-min=10.9
        LDFLAGS: -stdlib=libc++ -mmacosx-version-min=10.9
      run: |
        ./autogen.sh
        ./configure --disable-shared CC="ccache clang" CXX="ccache clang++" CXXFLAGS="${CXXFLAGS}" LDFLAGS="${LDFLAGS}"
        make -j 2
    - name: Run tests
      run: |
        ./test-suite/quantlib-test-suite --log_level=message
    - name: Run examples
      run: |
        make -C Examples check-examples
