name: Mac OS build with non-default configuration
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: [macos-11]
            shortname: default-11
          - os: [macos-11]
            shortname: stdclasses-11
            cxxflags: "-std=c++17"
            configureflags: --enable-std-classes --enable-std-optional
          - os: [macos-12]
            shortname: default-12
          - os: [macos-12]
            shortname: stdclasses-12
            cxxflags: "-std=c++17"
            configureflags: --enable-std-classes --enable-std-optional
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: |
        brew install automake boost
    - name: Build
      run: |
        ./autogen.sh
        ./configure --disable-shared --enable-error-lines --enable-error-functions --enable-tracing --enable-indexed-coupons --enable-extra-safety-checks --enable-sessions --enable-thread-safe-observer-pattern --enable-intraday --disable-faster-lazy-objects --enable-throwing-in-cycles --enable-null-as-functions ${{ matrix.configureflags }}  CC="clang" CXX="clang++" CXXFLAGS="-O2 -g0 -Wall -Werror -stdlib=libc++ -mmacosx-version-min=10.9 ${{ matrix.cxxflags }}" LDFLAGS="-stdlib=libc++ -mmacosx-version-min=10.9"
        make -j 3
    - name: Run tests
      run: |
        ./test-suite/quantlib-test-suite --log_level=message
    - name: Run examples
      run: |
        make -C Examples check-examples
