name: Linux build with address sanitizer enabled
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/lballabio/quantlib-devenv:rolling
    steps:
    - name: Set up git permissions
      run: |
        git config --global --add safe.directory $GITHUB_WORKSPACE
    - uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v3
      with:
        path: ~/.ccache
        key: linux-build-sanitizer-${{ github.ref }}-${{ github.head_ref }}-${{ hashFiles('**/*.hpp', '**/*.cpp') }}
        restore-keys: |
          linux-build-sanitizer-${{ github.ref }}-${{ github.head_ref }}-
          linux-build-sanitizer-${{ github.ref }}-
          linux-build-sanitizer-refs/heads/master-
          linux-build-sanitizer-
    - name: Compiler version
      run: |
        gcc --version
    - name: Build
      run: |
        ./autogen.sh
        ./configure --disable-static CC="ccache gcc" CXX="ccache g++" CXXFLAGS="-O2 -g0 -fsanitize=address -fno-omit-frame-pointer -Wall -Wno-unknown-pragmas -Werror"
        make -j 2
    - name: Run tests
      run: |
        ./test-suite/quantlib-test-suite --log_level=message
    - name: Run examples
      run: |
        make check-examples
