name: Close stale issues and PR
on:
  schedule:
    - cron: '30 1 * * *'
jobs:
  staleness-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue was automatically marked as stale because it has been open 60 days with no activity. Remove stale label or comment, or this will be closed in two weeks.'
          close-issue-message: 'This issue was automatically closed because it has been stalled for two weeks with no further activity.'
          stale-pr-message: 'This PR was automatically marked as stale because it has been open 60 days with no activity. Remove stale label or comment, or this will be closed in two weeks.'
          close-pr-message: 'This PR was automatically closed because it has been stalled for two weeks with no further activity.'
          days-before-stale: 60
          days-before-close: 14
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          exempt-issue-labels: 'help wanted,in progress'
          exempt-pr-labels: 'help wanted,in progress'
          exempt-all-milestones: true
