name: Check test times
on: [push, pull_request]
jobs:
  check-test-times:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v3
      with:
        path: ~/.ccache
        key: linux-build-times-${{ github.ref }}-${{ github.head_ref }}-${{ hashFiles('**/*.hpp', '**/*.cpp') }}
        restore-keys: |
          linux-build-times-${{ github.ref }}-${{ github.head_ref }}-
          linux-build-times-${{ github.ref }}-
          linux-build-times-refs/heads/master-
          linux-build-times-
    - name: Setup
      run: |
        sudo apt update
        sudo apt install -y libboost-all-dev autoconf automake libtool ccache
    - name: Build
      run: |
        ./autogen.sh
        ./configure --disable-static CC="ccache gcc" CXX="ccache g++" CXXFLAGS="-O2 -g0"
        make -j 2
    - name: Run tests
      run: |
        ./test-suite/quantlib-test-suite --logger=JUNIT,warning,faster.xml:HRF,message -- --faster
        ./test-suite/quantlib-test-suite --logger=JUNIT,warning,fast.xml:HRF,message -- --fast
        ./test-suite/quantlib-test-suite --logger=JUNIT,warning,all.xml:HRF,message
    - name: Save test times
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: ./all.xml
    - name: Check test times
      run: |
        python ./tools/check_test_times.py
